// <auto-generated />
using System;
using HaafaiAssetTrackingApp.Controllers.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HaafaiAssetTrackingApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250124184204_SetUpDatabase")]
    partial class SetUpDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HaafaiAssetTrackingApp.Models.Asset", b =>
                {
                    b.Property<int>("AssetNo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssetNo"));

                    b.Property<string>("AssetStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DiscardedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastReturnedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PurchasedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("staffId")
                        .HasColumnType("int");

                    b.HasKey("AssetNo");

                    b.HasIndex("staffId");

                    b.ToTable("Assets");

                    b.HasData(
                        new
                        {
                            AssetNo = 1,
                            AssetStatus = "Assigned",
                            AssetType = "Monitor",
                            AssignedDate = new DateTime(2023, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastReturnedDate = new DateTime(2023, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PurchasedDate = new DateTime(2023, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            staffId = 1
                        },
                        new
                        {
                            AssetNo = 2,
                            AssetStatus = "Not Assigned",
                            AssetType = "CPU",
                            LastReturnedDate = new DateTime(2023, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PurchasedDate = new DateTime(2023, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AssetNo = 3,
                            AssetStatus = "Discarded",
                            AssetType = "Keyboard",
                            DiscardedDate = new DateTime(2023, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PurchasedDate = new DateTime(2023, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("HaafaiAssetTrackingApp.Models.Staff", b =>
                {
                    b.Property<int>("StaffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("StaffId"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NicNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("StaffId");

                    b.ToTable("Staffs");

                    b.HasData(
                        new
                        {
                            StaffId = 1,
                            Department = "IT",
                            Name = "Jason David",
                            NicNo = "n333d3"
                        },
                        new
                        {
                            StaffId = 2,
                            Department = "Support",
                            Name = "Larry Frank",
                            NicNo = "n4f4f4f"
                        },
                        new
                        {
                            StaffId = 3,
                            Department = "HR",
                            Name = "Annie Taylor",
                            NicNo = "4fin4fn"
                        });
                });

            modelBuilder.Entity("HaafaiAssetTrackingApp.Models.StaffAssetHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AssetNo")
                        .HasColumnType("int");

                    b.Property<DateTime>("AssignedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("LastReturnedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("staffId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("staffId");

                    b.ToTable("staffAssetHistories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AssetNo = 1,
                            AssignedDate = new DateTime(2023, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastReturnedDate = new DateTime(2023, 1, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            staffId = 1
                        },
                        new
                        {
                            Id = 2,
                            AssetNo = 2,
                            AssignedDate = new DateTime(2023, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastReturnedDate = new DateTime(2023, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            staffId = 1
                        },
                        new
                        {
                            Id = 3,
                            AssetNo = 2,
                            AssignedDate = new DateTime(2023, 1, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            LastReturnedDate = new DateTime(2023, 1, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            staffId = 2
                        });
                });

            modelBuilder.Entity("HaafaiAssetTrackingApp.Models.Asset", b =>
                {
                    b.HasOne("HaafaiAssetTrackingApp.Models.Staff", "Staff")
                        .WithMany("Assets")
                        .HasForeignKey("staffId");

                    b.Navigation("Staff");
                });

            modelBuilder.Entity("HaafaiAssetTrackingApp.Models.StaffAssetHistory", b =>
                {
                    b.HasOne("HaafaiAssetTrackingApp.Models.Staff", "AssignedStaff")
                        .WithMany()
                        .HasForeignKey("staffId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignedStaff");
                });

            modelBuilder.Entity("HaafaiAssetTrackingApp.Models.Staff", b =>
                {
                    b.Navigation("Assets");
                });
#pragma warning restore 612, 618
        }
    }
}
